#!/bin/sh

project_name=columba

rm ${project_name}_log.txt
for ((i=1; i <= 10 ; i++)) do
	rm -rf /scratch/Projekty/dysertacja/${project_name}_models
	/usr/bin/time ./oumextractor -createdir -libdirs /scratch/dysertacja_projekty/${project_name}/lib /scratch/dysertacja_projekty/${project_name} /scratch/Projekty/dysertacja/${project_name}_models >> ${project_name}_log.txt
done
